name: Deploy MultiDocker
on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t bibi12/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true bibi12/react-test npm test
  
      - run: docker build -t bibi12/multi-client-10-15 ./client
      - run: docker build -t bibi12/multi-nginx-10-15 ./nginx
      - run: docker build -t bibi12/multi-server-10-15 ./server
      - run: docker build -t bibi12/multi-worker-10-15 ./worker
  
      - run: docker push bibi12/multi-client-10-15
      - run: docker push bibi12/multi-nginx-10-15
      - run: docker push bibi12/multi-server-10-15
      - run: docker push bibi12/multi-worker-10-15
  
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
  
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multi-container
          environment_name: Dockermulticontainer-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-635567262396
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true